### PR TITLE
fix typo contract -> contact

### PR DESCRIPTION
**Pull request by jermanuts**

### CODE REVIEW

**Comment by jermanuts** [comment]
hmm.. can you change URL redirect from https://deploy-preview-143--luminous-syrniki-f1e6b4.netlify.app/contract to https://deploy-preview-143--luminous-syrniki-f1e6b4.netlify.app/contact ?

image

**Comment by saturneric** [comment]
Ok, but I plan to merge this after v2.1.3 is released. Just wait for about a half month.

**Comment by jermanuts** [comment]
Ok, np :D

**Comment by saturneric** [comment]
Manual has moved to repo GpgFrontend-Manual, so I'll close this PR.

**Pull request closed without merging**
