### PR TITLE
Jermanuts wizard links update

### PR DESCRIPTION
**Pull request by jermanuts**
Reflects to the new docs links + other minor changes.

Please let me know if it work correctly on your local build.

Ignore old PR from Mar 24, 2024 https://github.com/saturneric/GpgFrontend/pull/143

### CODE REVIEW

**Comment by saturneric** [comment]
It's correct, and the newest commit was built smoothly. Ignore macOS build which is caused by an apple developer account issue. I will fix it later.

**Comment by saturneric** [comment]
Manual has moved to repo GpgFrontend-Manual, so I'll close this PR.

**Comment by jermanuts** [comment]
this is for the installation wizard.

**Comment by saturneric** [comment]
My fault. I'll take care of this later.

**Review by dav3yblaz3 — COMMENTED** [review]
thanks maybe this will work

**Comment by saturneric** [comment]
@jermanuts Okay, I'll deal with them.

**Pull request merged**
